---

- name: template torrc
  template: src=torrc dest=/etc/tor/torrc
    owner=root group=root mode=0644
  notify:
  - restart tor

- name: set capabilities for Tor binary
  capabilities:
    path=/usr/bin/tor
    capability=cap_net_bind_service=+ep

- meta: flush_handlers

- name: ensure tor is running
  service: name=tor state=running
