---
- hosts: all
  roles:
# XXX uber-paranoid openssh ansible role?
#    - { role: ansible-openssh-hardened,
#        backports_url: "http://ftp.de.debian.org/debian/",
#        backports_distribution_release: "wheezy-backports",
#        ssh_admin_ed25519pubkey_path: "/home/amnesia/.ssh/id_ed25519.pub",
#        sudo: yes
# XXX tlsdate?
#    - { role: ansible-tlsdate,
#        remove_ntp: yes,
#        sudo: yes
#      }
    - { role: ansible-tor,
        tor_BridgeRelay: 1,
        tor_PublishServerDescriptor: "0",
        tor_ExtORPort: "auto",
        tor_SocksPort: "0",
        tor_ORPort: 80,
        tor_ServerTransportListenAddr: "obfs4 [::]:443",
        tor_ServerTransportOptions: "obfs4 iat-mode=2",
        tor_ServerTransportPlugin: "obfs4 exec /usr/bin/obfs4proxy managed",
        tor_ExitPolicy: "reject *:*",
        tor_obfs4proxy_enabled: True,
        sudo: yes
      }
